### ISSUE TITLE
Issue with Pimcore Full Page Cache

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/server-side-matomo-tracking#8]
If you enable server side tracking with disableCookieSupport and setTokenAuth as described in the Readme file and the Full Page Cache of Pimcore is enabled, you'll get the following error:

> PHP Fatal error:  Uncaught Exception: Error:  you must call the function doTrackPageView or doTrackGoal from this class, before calling this method doBulkTrack() in /wwwfolder/vendor/piwik/piwik-php-tracker/PiwikTracker.php:723
> 
> Stack trace:
> #0 /wwwfolder/vendor/pimcore/server-side-matomo-tracking/src/Tracking/TrackingFacade.php(90): PiwikTracker->doBulkTrack()
> #1 /wwwfolder/vendor/pimcore/server-side-matomo-tracking/src/EventListener/TrackingListener.php(119): Pimcore\Bundle\ServerSideMatomoTrackingBundle\Tracking\TrackingFacade->doBulkTrackForAllTrackers()
> #2 /wwwfolder/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): Pimcore\Bundle\ServerSideMatomoTrackingBundle\EventListener\TrackingListener->onTerminate(Object(Symfony\Component\HttpKernel\Event\PostResponseEvent), 'kernel.terminat...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
> #3 /wwwfolder/vendor/symfony/symfony/src/Symfony/Component in /wwwfolder/vendor/piwik/piwik-php-tracker/PiwikTracker.php on line 723

Beside that, a request is made to the browser (containing something like this):

> Array ( [host] => Array ( [0] => localhost ) [user-agent] => Array ( [0] => Symfony/3.X ) [accept] => Array ( [0] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 ) [accept-language] => Array ( [0] => en-us,en;q=0.5 ) [accept-charset] => Array ( [0] => ISO-8859-1,utf-8;q=0.7,*;q=0.7 ) [forwarded] => Array ( [0] => for="127.0.0.1";host="localhost";proto=http ) [x-forwarded-for] => Array ( [0] => 127.0.0.1 ) [x-php-ob-level] => Array ( [0] => 0 ) )

This will lead to the delivery of an error page by Pimcore which is displayed right after the real page delivery in chrome browser.

Tested with Pimcore 5.7.1 and 0.1.0 of pimcore/server-side-matomo-tracking.

**Comment by fashxp** [comment]
ou, for that we have to listen for different events. 

can you try to listen to `kernel.request` instead of `kernel.response`? 
[here](https://github.com/pimcore/server-side-matomo-tracking/blob/a04eae1757c338022f4eecf3e7d1a0b01253bdc5/src/Resources/config/services.yml#L22) would be following line necessary: 
`- { name: kernel.event_listener, event: kernel.request, method: onResponse, priority: 7 }`

and the typehint [here](https://github.com/pimcore/server-side-matomo-tracking/blob/a04eae1757c338022f4eecf3e7d1a0b01253bdc5/src/EventListener/TrackingListener.php#L122) would need to be changed to `GetResponseEvent`. 

but i'm not sure though, if still everything is working.

**Comment by Cruiser13** [comment]
@fashxp this does sadly not fix the issue for me.

**Comment by fashxp** [comment]
@Cruiser13 hmm could you try to further debug that? For me it worked.
